apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-auth.name" . }}
data:
  auth_config.yml: |
    server:
      addr: ":{{ .Values.service.targetPort }}"
    token:
      issuer: "{{ .Values.configmap.data.token.issuer }}"  # Must match issuer in the Registry config.
      expiration: {{ .Values.configmap.data.token.expiration }}
{{- if .Values.secret.certificateName }}
      certificate: "/config/certs/{{ .Values.secret.certificateName}}"
{{- else }}
      certificate: "/config/certs/server.pem"
{{- end }}
{{- if .Values.secret.keyName }}
      key: "/config/certs/{{ .Values.secret.keyName }}"
{{- else }}
      key: "/config/certs/server.key"
{{- end }}
    users:
      {{ .Values.configmap.data.users | toYaml | nindent 6 }}
    acl:
      {{ .Values.configmap.data.acl | toYaml | nindent 6 }}
